import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

import '../cli/exceptions.dart';
import '../model/state/build_state.dart';
import 'build_assembler.dart';

/// File name of the side-car ledger written into each `build/<env>/` tree.
/// Mirrors the existing `.gitrinth-installed-<loader>-<version>` marker
/// the server installer drops alongside it.
const String ledgerFileName = '.gitrinth-state.yaml';

/// Returns the absolute path to the ledger for [envRoot].
String ledgerPathFor(Directory envRoot) => p.join(envRoot.path, ledgerFileName);

/// Paths that build never prunes even when they appear in the prior
/// ledger. Defense-in-depth: these paths shouldn't end up in a ledger
/// at all (the orchestrator never writes them through the managed
/// copy step), but we belt-and-suspenders the deletion loop.
bool isProtectedPath(String relativePath) {
  if (relativePath == ledgerFileName) return true;
  // Loader-installer marker (e.g. `.gitrinth-installed-forge-47.3.0`).
  if (relativePath.startsWith('.gitrinth-installed-')) return true;
  return false;
}

LedgerEnv ledgerEnvFor(BuildEnv env) => switch (env) {
  BuildEnv.client => LedgerEnv.client,
  BuildEnv.server => LedgerEnv.server,
};

/// Reads the ledger at [ledgerPath]. Returns an empty ledger when the
/// file is missing or unreadable — first builds and freshly-cleaned
/// trees both produce no prior state.
BuildLedger readLedgerOrEmpty(String ledgerPath, BuildEnv env) {
  final file = File(ledgerPath);
  if (!file.existsSync()) {
    return BuildLedger(
      gitrinthVersion: '',
      env: ledgerEnvFor(env),
      generatedAt: '',
    );
  }
  final dynamic raw;
  try {
    raw = loadYaml(file.readAsStringSync());
  } on YamlException {
    // Treat malformed ledgers as missing rather than blowing up the
    // build. The new ledger written at the end of this run will
    // overwrite it anyway.
    return BuildLedger(
      gitrinthVersion: '',
      env: ledgerEnvFor(env),
      generatedAt: '',
    );
  }
  if (raw is! Map) {
    return BuildLedger(
      gitrinthVersion: '',
      env: ledgerEnvFor(env),
      generatedAt: '',
    );
  }
  final filesRaw = raw['files'];
  final files = <String, LedgerSource>{};
  if (filesRaw is Map) {
    filesRaw.forEach((key, value) {
      if (key is! String || value is! Map) return;
      final kind = value['kind'];
      if (kind == 'mod-entry') {
        files[key] = LedgerModSource(
          section: value['section']?.toString() ?? '',
          slug: value['slug']?.toString() ?? '',
          sha512: (value['sha512'] as String?)?.toLowerCase(),
        );
      } else if (kind == 'file-entry') {
        files[key] = LedgerFileSource(
          key: value['key']?.toString() ?? key,
          preserve: value['preserve'] == true,
          sourcePath: value['source-path']?.toString() ?? '',
          sha512: (value['sha512'] as String?)?.toLowerCase(),
        );
      }
    });
  }
  final envName = raw['env']?.toString();
  return BuildLedger(
    gitrinthVersion: raw['gitrinth-version']?.toString() ?? '',
    env: envName == 'server' ? LedgerEnv.server : LedgerEnv.client,
    generatedAt: raw['generated-at']?.toString() ?? '',
    files: files,
  );
}

/// Writes [ledger] to [ledgerPath] in the canonical YAML shape.
/// Sections are deterministic (alphabetical destination keys) so the
/// ledger is diff-friendly when committed alongside a `build/` tree.
void writeLedger(String ledgerPath, BuildLedger ledger) {
  final buf = StringBuffer()
    ..writeln('# AUTO-GENERATED by gitrinth build. Do not edit by hand.')
    ..writeln('# Tracks files installed by the last build run so re-runs')
    ..writeln('# can prune obsolete files without touching loose user files.')
    ..writeln('gitrinth-version: ${_str(ledger.gitrinthVersion)}')
    ..writeln('env: ${ledger.env.name}')
    ..writeln('generated-at: ${_str(ledger.generatedAt)}');
  if (ledger.files.isEmpty) {
    buf.writeln('files: {}');
  } else {
    buf.writeln('files:');
    final entries = ledger.files.entries.toList()
      ..sort((a, b) => a.key.compareTo(b.key));
    for (final fileEntry in entries) {
      final dest = fileEntry.key;
      final src = fileEntry.value;
      buf.writeln('  ${_key(dest)}:');
      switch (src) {
        case LedgerModSource():
          buf.writeln('    kind: mod-entry');
          buf.writeln('    section: ${_str(src.section)}');
          buf.writeln('    slug: ${_str(src.slug)}');
          final sha512 = src.sha512;
          if (sha512 != null) {
            buf.writeln('    sha512: ${_str(sha512.toLowerCase())}');
          }
        case LedgerFileSource():
          buf.writeln('    kind: file-entry');
          buf.writeln('    key: ${_str(src.key)}');
          if (src.preserve) buf.writeln('    preserve: true');
          buf.writeln('    source-path: ${_str(src.sourcePath)}');
          final sha512 = src.sha512;
          if (sha512 != null) {
            buf.writeln('    sha512: ${_str(sha512.toLowerCase())}');
          }
      }
    }
  }
  final file = File(ledgerPath);
  file.parent.createSync(recursive: true);
  file.writeAsStringSync(buf.toString());
}

/// Diff helper: returns destination paths in [prior] that are not in
/// [desired]. Caller deletes these in the prune pass. Protected paths
/// (e.g. the ledger file itself, loader-installer markers) are filtered
/// out so we never prune them by mistake.
Set<String> obsoletePaths({
  required BuildLedger prior,
  required Set<String> desired,
}) {
  final out = <String>{};
  for (final path in prior.files.keys) {
    if (desired.contains(path)) continue;
    if (isProtectedPath(path)) continue;
    out.add(path);
  }
  return out;
}

/// Deletes [relPath] under [envRoot] and removes any empty parent
/// directories left behind, up to (but not including) [envRoot].
/// No-op when the file is missing.
void pruneFile({required Directory envRoot, required String relPath}) {
  final abs = p.normalize(p.join(envRoot.path, relPath));
  final inside = p.isWithin(envRoot.path, abs);
  if (!inside) {
    // Defense-in-depth: if a malicious or stale ledger entry escapes
    // the env root, refuse to delete and surface a validation error.
    throw ValidationError(
      'pruner: ledger entry "$relPath" resolves outside ${envRoot.path}; '
      'refusing to delete.',
    );
  }
  final file = File(abs);
  if (file.existsSync()) {
    file.deleteSync();
  }
  _pruneEmptyParents(Directory(p.dirname(abs)), stopAt: envRoot);
}

void _pruneEmptyParents(Directory dir, {required Directory stopAt}) {
  final stopPath = p.normalize(stopAt.path);
  var current = Directory(p.normalize(dir.path));
  while (true) {
    final currentPath = p.normalize(current.path);
    if (currentPath == stopPath) return;
    if (!p.isWithin(stopPath, currentPath)) return;
    if (!current.existsSync()) {
      current = current.parent;
      continue;
    }
    final isEmpty = current.listSync().isEmpty;
    if (!isEmpty) return;
    try {
      current.deleteSync();
    } on FileSystemException {
      return;
    }
    current = current.parent;
  }
}

String _key(String value) {
  if (_needsQuotes(value)) return _str(value);
  return value;
}

String _str(String value) {
  if (value.isEmpty) return '""';
  if (_needsQuotes(value)) {
    final escaped = value.replaceAll(r'\', r'\\').replaceAll('"', r'\"');
    return '"$escaped"';
  }
  return value;
}

bool _needsQuotes(String value) {
  if (value.isEmpty) return true;
  const reserved = {'yes', 'no', 'true', 'false', 'on', 'off', 'null', '~'};
  if (reserved.contains(value.toLowerCase())) return true;
  if (RegExp(r'^[-+]?\d+(\.\d+)?$').hasMatch(value)) return true;
  if (RegExp(
    r'[:#\[\]{},&*!|>%@`"'
    "'"
    r']',
  ).hasMatch(value)) {
    return true;
  }
  if (value.startsWith(' ') || value.endsWith(' ')) return true;
  if (value.contains('\n')) return true;
  return false;
}
