import 'mods_lock.dart';
import 'mods_yaml.dart';

/// Emits a deterministic YAML representation of [lock]. Sections are listed
/// in canonical order; entries within a section are alphabetical by slug.
String emitModsLock(ModsLock lock) {
  final buf = StringBuffer()
    ..writeln('# AUTO-GENERATED by gitrinth get. Do not edit by hand.')
    ..writeln('# Commit this file to git.')
    ..writeln('gitrinth-version: ${_str(lock.gitrinthVersion)}')
    ..writeln('loader:')
    ..writeln('  mods: ${lock.loader.mods.name}');
  if (lock.loader.shaders != null) {
    buf.writeln('  shaders: ${lock.loader.shaders!.name}');
  }
  if (lock.loader.plugins != null) {
    buf.writeln('  plugins: ${lock.loader.plugins!.name}');
  }
  buf.writeln('mc-version: ${_str(lock.mcVersion)}');

  _emitSection(buf, 'mods', lock.mods);
  _emitSection(buf, 'resource_packs', lock.resourcePacks);
  _emitSection(buf, 'data_packs', lock.dataPacks);
  _emitSection(buf, 'shaders', lock.shaders);
  return buf.toString();
}

void _emitSection(
  StringBuffer buf,
  String name,
  Map<String, LockedEntry> entries,
) {
  if (entries.isEmpty) {
    buf.writeln('$name: {}');
    return;
  }
  buf.writeln('$name:');
  final keys = entries.keys.toList()..sort();
  for (final slug in keys) {
    _emitEntry(buf, slug, entries[slug]!);
  }
}

void _emitEntry(StringBuffer buf, String slug, LockedEntry e) {
  buf.writeln('  ${_key(slug)}:');
  buf.writeln('    source: ${_sourceKindName(e.sourceKind)}');
  if (e.version != null) buf.writeln('    version: ${_str(e.version!)}');
  if (e.projectId != null) buf.writeln('    project-id: ${_str(e.projectId!)}');
  if (e.versionId != null) buf.writeln('    version-id: ${_str(e.versionId!)}');
  if (e.path != null) buf.writeln('    path: ${_str(e.path!)}');
  final f = e.file;
  if (f != null) {
    buf.writeln('    file:');
    buf.writeln('      name: ${_str(f.name)}');
    if (f.url != null) buf.writeln('      url: ${_str(f.url!)}');
    if (f.sha512 != null) buf.writeln('      sha512: ${_str(f.sha512!.toLowerCase())}');
    if (f.size != null) buf.writeln('      size: ${f.size}');
  }
  buf.writeln('    env: ${_envName(e.env)}');
  if (e.auto) buf.writeln('    auto: true');
}

String _envName(Environment e) => e.name;
String _sourceKindName(LockedSourceKind k) => k.name;

String _key(String slug) {
  if (_needsQuotes(slug)) return _str(slug);
  return slug;
}

String _str(String value) {
  if (value.isEmpty) return '""';
  if (_needsQuotes(value)) {
    final escaped = value.replaceAll(r'\', r'\\').replaceAll('"', r'\"');
    return '"$escaped"';
  }
  return value;
}

bool _needsQuotes(String value) {
  if (value.isEmpty) return true;
  // Reserved words and characters that change YAML parsing.
  const reserved = {
    'yes', 'no', 'true', 'false', 'on', 'off', 'null', '~',
  };
  if (reserved.contains(value.toLowerCase())) return true;
  if (RegExp(r'^[-+]?\d+(\.\d+)?$').hasMatch(value)) return true;
  // Conservative: any character that needs escaping.
  if (RegExp(r'[:#\[\]{},&*!|>%@`"' "'" r']').hasMatch(value)) return true;
  if (value.startsWith(' ') || value.endsWith(' ')) return true;
  if (value.contains('\n')) return true;
  return false;
}
