import 'mods_lock.dart';
import 'mods_yaml.dart' show ModLoader;

/// Emits a deterministic YAML representation of [lock]. Sections are listed
/// in canonical order; entries within a section are alphabetical by slug.
String emitModsLock(ModsLock lock) {
  final buf = StringBuffer()
    ..writeln('# AUTO-GENERATED by gitrinth get. Do not edit by hand.')
    ..writeln('# Commit this file to git.')
    ..writeln('gitrinth-version: ${_str(lock.gitrinthVersion)}')
    ..writeln('loader:');
  // `vanilla` is the no-mod-runtime sentinel — emit it bare with no
  // version tag. Real loaders always have a resolved version in the
  // lock and emit `<name>:<version>`.
  final modsName = lock.loader.mods.name;
  final modLoaderVersion = lock.loader.modLoaderVersion;
  if (lock.loader.mods == ModLoader.vanilla || modLoaderVersion == null) {
    buf.writeln('  mods: $modsName');
  } else {
    buf.writeln('  mods: ${_str("$modsName:$modLoaderVersion")}');
  }
  final shaders = lock.loader.shaders;
  if (shaders != null) {
    buf.writeln('  shaders: ${shaders.name}');
  }
  final plugins = lock.loader.plugins;
  if (plugins != null) {
    final pluginVersion = lock.loader.pluginLoaderVersion;
    if (pluginVersion == null) {
      buf.writeln('  plugins: ${plugins.name}');
    } else {
      buf.writeln('  plugins: ${_str("${plugins.name}:$pluginVersion")}');
    }
  }
  buf.writeln('mc-version: ${_str(lock.mcVersion)}');

  _emitSection(buf, 'mods', lock.mods);
  _emitSection(buf, 'resource_packs', lock.resourcePacks);
  _emitSection(buf, 'data_packs', lock.dataPacks);
  _emitSection(buf, 'shaders', lock.shaders);
  _emitSection(buf, 'plugins', lock.plugins);
  _emitFilesSection(buf, lock.files);
  return buf.toString();
}

void _emitFilesSection(StringBuffer buf, Map<String, LockedFileEntry> files) {
  if (files.isEmpty) {
    buf.writeln('files: {}');
    return;
  }
  buf.writeln('files:');
  final entries = files.entries.toList()
    ..sort((a, b) => a.key.compareTo(b.key));
  for (final fileEntry in entries) {
    final dest = fileEntry.key;
    final e = fileEntry.value;
    buf.writeln('  ${_key(dest)}:');
    buf.writeln('    path: ${_str(e.sourcePath)}');
    buf.writeln('    client: ${e.client.name}');
    buf.writeln('    server: ${e.server.name}');
    if (e.preserve) buf.writeln('    preserve: true');
    final sha512 = e.sha512;
    if (sha512 != null) {
      buf.writeln('    sha512: ${_str(sha512.toLowerCase())}');
    }
  }
}

void _emitSection(
  StringBuffer buf,
  String name,
  Map<String, LockedEntry> entries,
) {
  if (entries.isEmpty) {
    buf.writeln('$name: {}');
    return;
  }
  buf.writeln('$name:');
  final sortedEntries = entries.entries.toList()
    ..sort((a, b) => a.key.compareTo(b.key));
  for (final entry in sortedEntries) {
    _emitEntry(buf, entry.key, entry.value);
  }
}

void _emitEntry(StringBuffer buf, String slug, LockedEntry e) {
  buf.writeln('  ${_key(slug)}:');
  buf.writeln('    source: ${_sourceKindName(e.sourceKind)}');
  final version = e.version;
  if (version != null) buf.writeln('    version: ${_str(version)}');
  final projectId = e.projectId;
  if (projectId != null) buf.writeln('    project-id: ${_str(projectId)}');
  final versionId = e.versionId;
  if (versionId != null) buf.writeln('    version-id: ${_str(versionId)}');
  final path = e.path;
  if (path != null) buf.writeln('    path: ${_str(path)}');
  final f = e.file;
  if (f != null) {
    buf.writeln('    file:');
    buf.writeln('      name: ${_str(f.name)}');
    final url = f.url;
    if (url != null) buf.writeln('      url: ${_str(url)}');
    final sha1 = f.sha1;
    if (sha1 != null) {
      buf.writeln('      sha1: ${_str(sha1.toLowerCase())}');
    }
    final sha512 = f.sha512;
    if (sha512 != null) {
      buf.writeln('      sha512: ${_str(sha512.toLowerCase())}');
    }
    if (f.size != null) buf.writeln('      size: ${f.size}');
  }
  buf.writeln('    client: ${e.client.name}');
  buf.writeln('    server: ${e.server.name}');
  if (e.dependency != LockedDependencyKind.direct) {
    buf.writeln('    dependency: ${e.dependency.name}');
  }
  if (e.gameVersions.isNotEmpty) {
    final quoted = e.gameVersions.map(_str).join(', ');
    buf.writeln('    game-versions: [$quoted]');
  }
  if (e.acceptsMc.isNotEmpty) {
    final quoted = e.acceptsMc.map(_str).join(', ');
    buf.writeln('    accepts-mc: [$quoted]');
  }
}

String _sourceKindName(LockedSourceKind k) => k.name;

String _key(String slug) {
  if (_needsQuotes(slug)) return _str(slug);
  return slug;
}

String _str(String value) {
  if (value.isEmpty) return '""';
  if (_needsQuotes(value)) {
    final escaped = value.replaceAll(r'\', r'\\').replaceAll('"', r'\"');
    return '"$escaped"';
  }
  return value;
}

bool _needsQuotes(String value) {
  if (value.isEmpty) return true;
  // Reserved words and characters that change YAML parsing.
  const reserved = {'yes', 'no', 'true', 'false', 'on', 'off', 'null', '~'};
  if (reserved.contains(value.toLowerCase())) return true;
  if (RegExp(r'^[-+]?\d+(\.\d+)?$').hasMatch(value)) return true;
  // Conservative: any character that needs escaping.
  if (RegExp(
    r'[:#\[\]{},&*!|>%@`"'
    "'"
    r']',
  ).hasMatch(value)) {
    return true;
  }
  if (value.startsWith(' ') || value.endsWith(' ')) return true;
  if (value.contains('\n')) return true;
  return false;
}
