// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by asset_strings_builder.
//
// Source assets:
//   gitignoreTemplate <- assets/template/gitignore.tmpl
//   modrinthIgnoreTemplate <- assets/template/modrinth_ignore.tmpl
//   modsYamlTemplate <- assets/template/mods.yaml
//   readmeTemplate <- assets/template/README.md

import 'dart:convert';

final String gitignoreTemplate = utf8.decode(base64.decode('IyBDcmVhdGVkIGJ5IGBnaXRyaW50aCBjcmVhdGVgCi5naXRyaW50aF90b29sLwpidWlsZC8KKi5tcnBhY2sK'));

final String modrinthIgnoreTemplate = utf8.decode(base64.decode('IyAubW9kcmludGhfaWdub3JlJ2QgZmlsZXMgYXJlIGV4Y2x1ZGVkIGZyb20gcHVibGlzaGluZy4KIyBGb2xsb3dzIC5naXRpZ25vcmUgc3ludGF4LgouZ2l0cmludGhfdG9vbC8KYnVpbGQvCioubXJwYWNrCg=='));

final String modsYamlTemplate = utf8.decode(base64.decode('c2x1Zzoge3tzbHVnfX0KbmFtZToge3tuYW1lfX0KdmVyc2lvbjoge3t2ZXJzaW9ufX0KZGVzY3JpcHRpb246IHt7ZGVzY3JpcHRpb259fQoKbG9hZGVyOiB7e2xvYWRlcn19Cm1jLXZlcnNpb246IHt7bWMtdmVyc2lvbn19Cgp0b29saW5nOgogIGdpdHJpbnRoOiAiPj17e2dpdHJpbnRoLXZlcnNpb259fSA8e3tnaXRyaW50aC1uZXh0LW1ham9yfX0iCgptb2RzOgoKcmVzb3VyY2VfcGFja3M6CgpkYXRhX3BhY2tzOgoKc2hhZGVyczoKCnBsdWdpbnM6Cg=='));

final String readmeTemplate = utf8.decode(base64.decode('IyB7e25hbWV9fQoKe3tkZXNjcmlwdGlvbn19CgojIyBSZXF1aXJlbWVudHMKCi0gTWluZWNyYWZ0IHt7bWMtdmVyc2lvbn19Ci0ge3tsb2FkZXJ9fQo='));

