// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by asset_strings_builder.
//
// Source assets:
//   gitignoreTemplate <- assets/template/gitignore.tmpl
//   modrinthIgnoreTemplate <- assets/template/modrinth_ignore.tmpl
//   modsYamlTemplate <- assets/template/mods.yaml
//   readmeTemplate <- assets/template/README.md

import 'dart:convert';

final String gitignoreTemplate = utf8.decode(
  base64.decode(
    'IyBDcmVhdGVkIGJ5IGBnaXRyaW50aCBjcmVhdGVgCi5naXRyaW50aF90b29sLwpidWlsZC8KKi5tcnBhY2sKKi5sb2cK',
  ),
);
final String modrinthIgnoreTemplate = utf8.decode(
  base64.decode(
    'IyAubW9kcmludGhfaWdub3JlJ2QgZmlsZXMgYXJlIGV4Y2x1ZGVkIGZyb20gcHVibGlzaGluZy4KIyBGb2xsb3dzIC5naXRpZ25vcmUgc3ludGF4LgouZ2l0cmludGhfdG9vbC8KYnVpbGQvCioubXJwYWNrCioubG9nCg==',
  ),
);
final String modsYamlTemplate = utf8.decode(
  base64.decode(
    'c2x1Zzoge3tzbHVnfX0NCm5hbWU6IHt7bmFtZX19DQp2ZXJzaW9uOiB7e3ZlcnNpb259fQ0KZGVzY3JpcHRpb246IHt7ZGVzY3JpcHRpb259fQ0KDQpsb2FkZXI6Cnt7bG9hZGVyLWJsb2NrfX0KbWMtdmVyc2lvbjoge3ttYy12ZXJzaW9ufX0KDQp0b29saW5nOg0KICBnaXRyaW50aDogIj49e3tnaXRyaW50aC12ZXJzaW9ufX0gPHt7Z2l0cmludGgtbmV4dC1tYWpvcn19Ig0KDQptb2RzOg0KICBnbG9iYWxwYWNrczogc3RhYmxlDQoNCnJlc291cmNlX3BhY2tzOg0KDQpkYXRhX3BhY2tzOg0KDQpzaGFkZXJzOg0KDQpwbHVnaW5zOg0K',
  ),
);
final String readmeTemplate = utf8.decode(
  base64.decode(
    'IyB7e25hbWV9fQoKe3tkZXNjcmlwdGlvbn19CgojIyBSZXF1aXJlbWVudHMKCnt7cmVxdWlyZW1lbnRzfX0K',
  ),
);
