import 'dart:async';
import 'dart:convert';

import 'package:build/build.dart';
import 'package:code_builder/code_builder.dart';
import 'package:dart_style/dart_style.dart';

/// Materialises a set of on-disk asset files as Dart `String`
/// declarations in a single generated library.
///
/// Each asset's bytes are base64-encoded into the generated source, then
/// decoded once at first access via a top-level `final`. This keeps the
/// generated file binary-safe (no escape-sequence quirks for arbitrary
/// bytes) and roughly the same size as the source for typical text assets.
///
/// Configured via `build.yaml` in the consumer package:
///
/// ```yaml
/// targets:
///   $default:
///     builders:
///       asset_strings_builder:asset_strings:
///         enabled: true
///         options:
///           assets:
///             myConstantName: assets/path/to/file.txt
/// ```
class AssetStringsBuilder implements Builder {
  /// Map of constant name → package-relative asset path.
  final Map<String, String> assets;

  AssetStringsBuilder(this.assets);

  factory AssetStringsBuilder.fromOptions(BuilderOptions options) {
    final raw = options.config['assets'];
    if (raw == null) {
      return AssetStringsBuilder(const {});
    }
    if (raw is! Map) {
      throw ArgumentError(
        'asset_strings_builder: `assets` option must be a map of '
        'constantName → assetPath, got ${raw.runtimeType}.',
      );
    }
    final parsed = <String, String>{};
    raw.forEach((key, value) {
      if (key is! String || value is! String) {
        throw ArgumentError(
          'asset_strings_builder: every entry in `assets` must be '
          'String → String, got $key (${key.runtimeType}) → '
          '$value (${value.runtimeType}).',
        );
      }
      parsed[key] = value;
    });
    return AssetStringsBuilder(parsed);
  }

  @override
  Map<String, List<String>> get buildExtensions => const {
    r'$package$': ['lib/src/asset_strings.g.dart'],
  };

  @override
  FutureOr<void> build(BuildStep buildStep) async {
    if (assets.isEmpty) {
      log.warning(
        'asset_strings_builder: no assets configured; skipping generation. '
        'Add an `assets:` map under this builder\'s `options:` in build.yaml.',
      );
      return;
    }

    final package = buildStep.inputId.package;
    final entries = assets.entries.toList()
      ..sort((a, b) => a.key.compareTo(b.key));

    final fields = <Field>[];
    for (final entry in entries) {
      final assetId = AssetId(package, entry.value);
      final bytes = await buildStep.readAsBytes(assetId);
      final encoded = base64.encode(bytes);
      fields.add(
        Field(
          (b) => b
            ..name = entry.key
            ..type = refer('String')
            ..modifier = FieldModifier.final$
            ..assignment = refer('utf8').property('decode').call([
              refer('base64').property('decode').call([literalString(encoded)]),
            ]).code,
        ),
      );
    }

    final library = Library(
      (b) => b
        ..comments.addAll([
          'GENERATED CODE - DO NOT MODIFY BY HAND',
          'Generated by asset_strings_builder.',
          '',
          'Source assets:',
          for (final entry in entries) '  ${entry.key} <- ${entry.value}',
        ])
        ..directives.add(Directive.import('dart:convert'))
        ..body.addAll(fields),
    );

    final emitter = DartEmitter(useNullSafetySyntax: true);
    final formatter = DartFormatter(
      languageVersion: DartFormatter.latestLanguageVersion,
    );
    final source = formatter.format('${library.accept(emitter)}');

    await buildStep.writeAsString(buildStep.allowedOutputs.single, source);
  }
}
