import 'dart:async';
import 'dart:convert';

import 'package:build/build.dart';

/// Materialises a set of on-disk asset files as Dart `String`
/// declarations in a single generated library.
///
/// Each asset's bytes are base64-encoded into the generated source, then
/// decoded once at first access via a top-level `final`. This keeps the
/// generated file binary-safe (no escape-sequence quirks for arbitrary
/// bytes) and roughly the same size as the source for typical text assets.
///
/// Configured via `build.yaml` in the consumer package:
///
/// ```yaml
/// targets:
///   $default:
///     builders:
///       asset_strings_builder:asset_strings:
///         enabled: true
///         options:
///           assets:
///             myConstantName: assets/path/to/file.txt
/// ```
class AssetStringsBuilder implements Builder {
  /// Map of constant name → package-relative asset path.
  final Map<String, String> assets;

  AssetStringsBuilder(this.assets);

  factory AssetStringsBuilder.fromOptions(BuilderOptions options) {
    final raw = options.config['assets'];
    if (raw == null) {
      return AssetStringsBuilder(const {});
    }
    if (raw is! Map) {
      throw ArgumentError(
        'asset_strings_builder: `assets` option must be a map of '
        'constantName → assetPath, got ${raw.runtimeType}.',
      );
    }
    final parsed = <String, String>{};
    raw.forEach((key, value) {
      if (key is! String || value is! String) {
        throw ArgumentError(
          'asset_strings_builder: every entry in `assets` must be '
          'String → String, got $key (${key.runtimeType}) → '
          '$value (${value.runtimeType}).',
        );
      }
      parsed[key] = value;
    });
    return AssetStringsBuilder(parsed);
  }

  @override
  Map<String, List<String>> get buildExtensions => const {
        r'$package$': ['lib/src/asset_strings.g.dart'],
      };

  @override
  FutureOr<void> build(BuildStep buildStep) async {
    if (assets.isEmpty) {
      log.warning(
        'asset_strings_builder: no assets configured; skipping generation. '
        'Add an `assets:` map under this builder\'s `options:` in build.yaml.',
      );
      return;
    }

    final package = buildStep.inputId.package;
    final entries = assets.entries.toList()
      ..sort((a, b) => a.key.compareTo(b.key));

    final buffer = StringBuffer()
      ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND')
      ..writeln('// Generated by asset_strings_builder.')
      ..writeln('//')
      ..writeln('// Source assets:');
    for (final entry in entries) {
      buffer.writeln('//   ${entry.key} <- ${entry.value}');
    }
    buffer
      ..writeln()
      ..writeln("import 'dart:convert';")
      ..writeln();

    for (final entry in entries) {
      final assetId = AssetId(package, entry.value);
      final bytes = await buildStep.readAsBytes(assetId);
      final encoded = base64.encode(bytes);
      buffer
        ..writeln(
          'final String ${entry.key} = '
          "utf8.decode(base64.decode('$encoded'));",
        )
        ..writeln();
    }

    final output = buildStep.allowedOutputs.single;
    await buildStep.writeAsString(output, buffer.toString());
  }
}
